### ISSUE TITLE
License not recognised by GitHub

### ISSUE THREAD

**Issue by nikos912000** [ExpediaGroup/rhapsody#29]
**Describe the bug**

The license is still not recognised by GitHub which is a bit annoying!

**To Reproduce**

See the license section in the repo's main page.

**Expected behavior**

License shows as Apache 2.0.

**Additional context**

Possible reasons:
- Since there was a bit missing from the Apache license, GitHub might be using a cached version.
- We've both a `LICENSE` and a `LICENSE_HEADER` file which is possibly causing issues. GitHub's using a custom installation of [licensee](https://github.com/licensee/licensee) but not sure what kind of name checks they apply. A quick workaround would be to rename the `LICENSE_HEADER`.

Any chance to wipe out the existing one and add the Apache from the GitHub UI?

**Comment by Sage-Pierce** [comment]
Gonna see about following this doc to fix this: https://stackoverflow.com/questions/31639059/how-to-add-license-to-an-existing-github-project

**Comment by Sage-Pierce** [comment]
> Possible reasons:
> - Since there was a bit missing from the Apache license, GitHub might be using a cached version.
> - We've both a LICENSE and a LICENSE_HEADER file which is possibly causing issues. GitHub's using a custom installation of licensee but not sure what kind of name checks they apply. A quick workaround would be to rename the LICENSE_HEADER.

I've eliminated both of these possibilities. Gonna try the `delete and replace with GitHub UI route`

**Comment by Sage-Pierce** [comment]
Deletion and re-adding worked!
![image](https://user-images.githubusercontent.com/5396306/71191590-58bf1c80-224c-11ea-8839-53d55c39d9ee.png)
