### ISSUE TITLE
Bump to Newer Versions of Kafka and Confluent

### ISSUE THREAD

**Issue by Sage-Pierce** [ExpediaGroup/rhapsody#37]
**Describe the feature**

We're currently on older versions of Kafka and Confluent, 2.0.0 and 4.1.3, respectively. These are fairly old versions at around ~1.5 years old (at time of issue creation).

Let's at least bump these to 2.2.1 and 5.2.1, respectively to be less than a year old on them. Note that I'm initially targeting these versions to avoid other required dependency bumps on things like Jackson.

Note: May also require going from `kafka_2.11` to `kafka_2.12` for testing purposes

**Rational**

Let's try not to be too old on dependencies

**Comment by cricket007** [comment]
Scala 2.12 has been around long enough, although, you should really just need `kafka-clients`. As far as integration tests go, `testcontainers` or `spring-kafka` are typically used instead in most OSS repos I've come across.
